#!/bin/sh

Containers=$(docker container ls --format='{{.ID}}')
echo $Containers

for container in $Containers
do
	echo "Now It's time to kill the running container :- "$container
	killingContainer=$(docker kill $container)
	echo "Successfully killed container :- "$killingContainer
done



