#!/bin/sh

Containers=$(docker ps  --format='{{.ID}}')
echo $Containers

for container in $Containers
do
	echo "Stopping the running container :- "$container
	killingContainer=$(docker kill $container)
	echo "Successfully killed container :- "$killingContainer
done



